# Generated by Django 2.2.16 on 2022-02-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_follow',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
    ]
